<?php include 'includes/header.php';

// REQUIRE HACE LA MISMA FUNCION QUE INCLUDE, ES DECIR, LLAMAR A ORO ARCHIVO
// INLUDES ENFOCADO EN LLAMAR A TEMPLATES/PLANTILLAS
// REQUIRE ENFOCADO EN LLAMAR A FUNCIONES
// REQUIRE_ONCE SOLO INCLUYE EL ARCHIVO UNA VEZ


// CREAMOS UN ARCHIVO NUEVO DE FUNCIONES.PHP
require 'funciones.php';

iniciarApp();



include 'includes/footer.php';